import flax.linen as flax_nn

HOPPER_IRL_CONFIG = {
    "log_gen_every": 1000,
    "reward_net_hsize": [128, 128],
    "reward_net_sigmoid": False,
    "wandb_log": True,
    "plot": False,
    "train_rng": "SAME",
    "save_to_file": False,
    "reward_type": "REWARD_STATE",
    "reward_normalize": True,
    "real_reward_type": "IRL_STATE",
    "loss": "IRL",
    "discr_batch_size": 4096,
    "seed": 1,
    "seeds": 5,
    "num_eval_envs": 50,
    "irl_lrate_init": 6e-3,
    "inner_lr_linear": True,
    "inner_lr": 3e-4,
    "inner_steps": 10,
    "discr_trans_decay": 550,
    "discr_updates_every": 1,
    "discr_updates": 11,
    "discr_l2_loss": 0.0,
    "dual": False,
    "discr_schedule_type": "linear",
    "discr_final_lr": 6e-7,
    "run_test": False,
    "discr_loss": "bce",
    "num_updates_inner_loop": 1,
}

ANT_IRL_CONFIG = {
    "log_gen_every": 1000,
    "reward_net_hsize": [128, 128],
    "reward_net_sigmoid": False,
    "wandb_log": True,
    "plot": False,
    "train_rng": "SAME",
    "save_to_file": False,
    "reward_type": "REWARD_STATE",
    "reward_normalize": True,
    "real_reward_type": "IRL_STATE",
    "loss": "IRL",
    "discr_batch_size": 4096,
    "seed": 1,
    "seeds": 5,
    "num_eval_envs": 50,
    "irl_lrate_init": 6e-3,
    "inner_lr_linear": True,
    "inner_lr": 3e-4,
    "inner_steps": 10,
    "discr_trans_decay": 550,
    "discr_updates_every": 1,
    "discr_updates": 11,
    "discr_l2_loss": 0.0,
    "dual": False,
    "discr_schedule_type": "linear",
    "discr_final_lr": 6e-7,
    "run_test": False,
    "discr_loss": "bce",
    "num_updates_inner_loop": 1,
}

WALKER_IRL_CONFIG = {
    "log_gen_every": 1000,
    "reward_net_hsize": [128, 128],
    "reward_net_sigmoid": False,
    "wandb_log": True,
    "plot": False,
    "train_rng": "SAME",
    "save_to_file": False,
    "reward_type": "REWARD_STATE",
    "reward_normalize": True,
    "real_reward_type": "IRL_STATE",
    "loss": "IRL",
    "discr_batch_size": 4096,
    "seed": 1,
    "seeds": 5,
    "num_eval_envs": 50,
    "irl_lrate_init": 6e-3,
    "inner_lr_linear": True,
    "inner_lr": 3e-4,
    "inner_steps": 10,
    "discr_trans_decay": 550,
    "discr_updates_every": 1,
    "discr_updates": 11,
    "discr_l2_loss": 0.0,
    "dual": False,
    "discr_schedule_type": "linear",
    "discr_final_lr": 6e-7,
    "run_test": False,
    "discr_loss": "bce",
    "num_updates_inner_loop": 1,
}


HALFCHEETAH_IRL_CONFIG = {
    "log_gen_every": 1000,
    "reward_net_hsize": [128, 128],
    "reward_net_sigmoid": False,
    "wandb_log": True,
    "plot": False,
    "train_rng": "SAME",
    "save_to_file": False,
    "reward_type": "REWARD_STATE",
    "reward_normalize": True,
    "real_reward_type": "IRL_STATE",
    "loss": "IRL",
    "discr_batch_size": 4096,
    "seed": 1,
    "seeds": 5,
    "num_eval_envs": 50,
    "irl_lrate_init": 6e-3,
    "inner_lr_linear": True,
    "inner_lr": 3e-4,
    "inner_steps": 10,
    "discr_trans_decay": 550,
    "discr_updates_every": 1,
    "discr_updates": 11,
    "discr_l2_loss": 0.0,
    "dual": False,
    "discr_schedule_type": "linear",
    "discr_final_lr": 6e-7,
    "run_test": False,
    "discr_loss": "bce",
    "num_updates_inner_loop": 1,
}

HUMANOID_IRL_CONFIG = {
    "log_gen_every": 1000,
    "reward_net_hsize": [128, 128],
    "reward_net_sigmoid": False,
    "wandb_log": True,
    "plot": False,
    "train_rng": "SAME",
    "save_to_file": False,
    "reward_type": "REWARD_STATE",
    "reward_normalize": True,
    "real_reward_type": "IRL_STATE",
    "loss": "IRL",
    "discr_batch_size": 4096,
    "seed": 1,
    "seeds": 5,
    "num_eval_envs": 50,
    "irl_lrate_init": 6e-3,
    "inner_lr_linear": True,
    "inner_lr": 3e-4,
    "inner_steps": 10,
    "discr_trans_decay": 550,
    "discr_updates_every": 1,
    "discr_updates": 11,
    "discr_l2_loss": 0.0,
    "dual": False,
    "discr_schedule_type": "linear",
    "discr_final_lr": 6e-7,
    "run_test": False,
    "discr_loss": "bce",
    "num_updates_inner_loop": 1,
}
